services:
  dbus-canopen-motordrive-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace/dbus-canopen-motordrive
      - "${VELIB_PATH}:/workspace/velib"
    container_name: dbus-canopen-motordrive-build
    platform: linux/amd64
    tty: true
    stdin_open: true
    command: bash