services:
  dbus-sevcon-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace/dbus-sevcon
      - "${VELIB_PATH}:/workspace/velib"
    container_name: dbus-sevcon-build
    platform: linux/amd64
    tty: true
    stdin_open: true
    command: bash