name: Check formatting

on:
  push:
    branches:
      - '**'

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install clang-format 20
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20

      - name: Check formatting
        run: ./scripts/check-formatting.sh